# docker-compose.yml
version: '3.9'

services:
  bash-learn:
    tty: true
    stdin_open: true
    image: kalilinux/kali-rolling
    #image: bash
    volumes:
      - type: bind
        source: .
        target: /app/
